"""A one-time snapshot (taken 2026-08-21) of team icon URLs from
https://flair.redditcfb.com/flairwizard.php?family=FBS - small icons
purpose-built for use as a Reddit flair, which crop far better into a
Discord role icon than a full team logo does. Not a live integration:
that site has no documented API, just an HTML page meant for a human to
browse, so this was pulled once and hardcoded rather than scraped on
every role creation. Where a team has multiple icon variants on file
(e.g. an alternate or trophy version), the one with the most Reddit
users on it was kept. Falls back to the CFBD logo (see flair.py) for
any team not in this table - mainly recent FBS transitions the site
hasn't added yet, e.g. North Dakota State, Sacramento State."""

FLAIR_ICON_URLS = {
    'Air Force': 'https://cdn.redditcfb.com/60x40/cfb/airforce.png',
    'Akron': 'https://cdn.redditcfb.com/60x40/cfb/akron.png',
    'Alabama': 'https://cdn.redditcfb.com/60x40/cfb/alabama.png',
    'App State': 'https://cdn.redditcfb.com/60x40/cfb/appalachianstate.png',
    'Arizona': 'https://cdn.redditcfb.com/60x40/cfb/arizona.png',
    'Arizona State': 'https://cdn.redditcfb.com/60x40/cfb/arizonastate.png',
    'Arkansas': 'https://cdn.redditcfb.com/60x40/cfb/arkansas.png',
    'Arkansas State': 'https://cdn.redditcfb.com/60x40/cfb/arkansasstate.png',
    'Army': 'https://cdn.redditcfb.com/60x40/cfb/army.png',
    'Auburn': 'https://cdn.redditcfb.com/60x40/cfb/auburn.png',
    'BYU': 'https://cdn.redditcfb.com/60x40/cfb/byu.png',
    'Ball State': 'https://cdn.redditcfb.com/60x40/cfb/ballstate.png',
    'Baylor': 'https://cdn.redditcfb.com/60x40/cfb/baylor.png',
    'Boise State': 'https://cdn.redditcfb.com/60x40/cfb/boisestate.png',
    'Boston College': 'https://cdn.redditcfb.com/60x40/cfb/bostoncollege.png',
    'Bowling Green': 'https://cdn.redditcfb.com/60x40/cfb/bowlinggreen.png',
    'Buffalo': 'https://cdn.redditcfb.com/60x40/cfb/buffalo.png',
    'California': 'https://cdn.redditcfb.com/60x40/cfb/california.png',
    'Central Michigan': 'https://cdn.redditcfb.com/60x40/cfb/centralmichigan.png',
    'Charlotte': 'https://cdn.redditcfb.com/60x40/cfb/charlotte.png',
    'Cincinnati': 'https://cdn.redditcfb.com/60x40/cfb/cincinnati.png',
    'Clemson': 'https://cdn.redditcfb.com/60x40/cfb/clemson.png',
    'Coastal Carolina': 'https://cdn.redditcfb.com/60x40/cfb/coastalcarolina.png',
    'Colorado': 'https://cdn.redditcfb.com/60x40/cfb/colorado.png',
    'Colorado State': 'https://cdn.redditcfb.com/60x40/cfb/coloradostate.png',
    'Delaware': 'https://cdn.redditcfb.com/60x40/cfb/delaware.png',
    'Duke': 'https://cdn.redditcfb.com/60x40/cfb/duke.png',
    'East Carolina': 'https://cdn.redditcfb.com/60x40/cfb/ecu.png',
    'Eastern Michigan': 'https://cdn.redditcfb.com/60x40/cfb/easternmichigan.png',
    'Florida': 'https://cdn.redditcfb.com/60x40/cfb/florida.png',
    'Florida Atlantic': 'https://cdn.redditcfb.com/60x40/cfb/fau.png',
    'Florida International': 'https://cdn.redditcfb.com/60x40/cfb/fiu.png',
    'Florida State': 'https://cdn.redditcfb.com/60x40/cfb/floridastate.png',
    'Fresno State': 'https://cdn.redditcfb.com/60x40/cfb/fresnostate.png',
    'Georgia': 'https://cdn.redditcfb.com/60x40/cfb/georgia.png',
    'Georgia Southern': 'https://cdn.redditcfb.com/60x40/cfb/georgiasouthern.png',
    'Georgia State': 'https://cdn.redditcfb.com/60x40/cfb/georgiastate.png',
    'Georgia Tech': 'https://cdn.redditcfb.com/60x40/cfb/georgiatech.png',
    "Hawai'i": 'https://cdn.redditcfb.com/60x40/cfb/hawaii.png',
    'Houston': 'https://cdn.redditcfb.com/60x40/cfb/houston.png',
    'Illinois': 'https://cdn.redditcfb.com/60x40/cfb/illinois.png',
    'Indiana': 'https://cdn.redditcfb.com/60x40/cfb/indiana.png',
    'Iowa': 'https://cdn.redditcfb.com/60x40/cfb/iowa.png',
    'Iowa State': 'https://cdn.redditcfb.com/60x40/cfb/iowastate.png',
    'Jacksonville State': 'https://cdn.redditcfb.com/60x40/cfb/jacksonvillestate.png',
    'James Madison': 'https://cdn.redditcfb.com/60x40/cfb/jamesmadison.png',
    'Kansas': 'https://cdn.redditcfb.com/60x40/cfb/kansas.png',
    'Kansas State': 'https://cdn.redditcfb.com/60x40/cfb/kansasstate.png',
    'Kennesaw State': 'https://cdn.redditcfb.com/60x40/cfb/kennesawstate.png',
    'Kent State': 'https://cdn.redditcfb.com/60x40/cfb/kentstate.png',
    'Kentucky': 'https://cdn.redditcfb.com/60x40/cfb/kentucky.png',
    'LSU': 'https://cdn.redditcfb.com/60x40/cfb/lsu.png',
    'Liberty': 'https://cdn.redditcfb.com/60x40/cfb/liberty.png',
    'Louisiana': 'https://cdn.redditcfb.com/60x40/cfb/louisiana.png',
    'Louisiana Tech': 'https://cdn.redditcfb.com/60x40/cfb/louisianatech.png',
    'Louisville': 'https://cdn.redditcfb.com/60x40/cfb/louisville.png',
    'Marshall': 'https://cdn.redditcfb.com/60x40/cfb/marshall.png',
    'Maryland': 'https://cdn.redditcfb.com/60x40/cfb/maryland.png',
    'Massachusetts': 'https://cdn.redditcfb.com/60x40/cfb/umass.png',
    'Memphis': 'https://cdn.redditcfb.com/60x40/cfb/memphis.png',
    'Miami': 'https://cdn.redditcfb.com/60x40/cfb/miami.png',
    'Miami (OH)': 'https://cdn.redditcfb.com/60x40/cfb/miamioh.png',
    'Michigan': 'https://cdn.redditcfb.com/60x40/cfb/michigan.png',
    'Michigan State': 'https://cdn.redditcfb.com/60x40/cfb/michiganstate.png',
    'Middle Tennessee': 'https://cdn.redditcfb.com/60x40/cfb/middletennessee.png',
    'Minnesota': 'https://cdn.redditcfb.com/60x40/cfb/minnesota.png',
    'Mississippi State': 'https://cdn.redditcfb.com/60x40/cfb/mississippistate.png',
    'Missouri': 'https://cdn.redditcfb.com/60x40/cfb/missouri.png',
    'Missouri State': 'https://cdn.redditcfb.com/60x40/cfb/missouristate.png',
    'NC State': 'https://cdn.redditcfb.com/60x40/cfb/ncstate.png',
    'Navy': 'https://cdn.redditcfb.com/60x40/cfb/navy.png',
    'Nebraska': 'https://cdn.redditcfb.com/60x40/cfb/nebraska.png',
    'Nevada': 'https://cdn.redditcfb.com/60x40/cfb/nevada.png',
    'New Mexico': 'https://cdn.redditcfb.com/60x40/cfb/newmexico.png',
    'New Mexico State': 'https://cdn.redditcfb.com/60x40/cfb/newmexicostate.png',
    'North Carolina': 'https://cdn.redditcfb.com/60x40/cfb/northcarolina.png',
    'North Texas': 'https://cdn.redditcfb.com/60x40/cfb/northtexas.png',
    'Northern Illinois': 'https://cdn.redditcfb.com/60x40/cfb/northernillinois.png',
    'Northwestern': 'https://cdn.redditcfb.com/60x40/cfb/northwestern.png',
    'Notre Dame': 'https://cdn.redditcfb.com/60x40/cfb/notredame.png',
    'Ohio': 'https://cdn.redditcfb.com/60x40/cfb/ohio.png',
    'Ohio State': 'https://cdn.redditcfb.com/60x40/cfb/ohiostate.png',
    'Oklahoma': 'https://cdn.redditcfb.com/60x40/cfb/oklahoma.png',
    'Oklahoma State': 'https://cdn.redditcfb.com/60x40/cfb/oklahomastate.png',
    'Old Dominion': 'https://cdn.redditcfb.com/60x40/cfb/olddominion.png',
    'Ole Miss': 'https://cdn.redditcfb.com/60x40/cfb/olemiss.png',
    'Oregon': 'https://cdn.redditcfb.com/60x40/cfb/oregon.png',
    'Oregon State': 'https://cdn.redditcfb.com/60x40/cfb/oregonstate.png',
    'Penn State': 'https://cdn.redditcfb.com/60x40/cfb/pennstate.png',
    'Pittsburgh': 'https://cdn.redditcfb.com/60x40/cfb/pittsburgh.png',
    'Purdue': 'https://cdn.redditcfb.com/60x40/cfb/purdue.png',
    'Rice': 'https://cdn.redditcfb.com/60x40/cfb/rice.png',
    'Rutgers': 'https://cdn.redditcfb.com/60x40/cfb/rutgers.png',
    'SMU': 'https://cdn.redditcfb.com/60x40/cfb/smu.png',
    'Sam Houston': 'https://cdn.redditcfb.com/60x40/cfb/samhoustonstate.png',
    'San Diego State': 'https://cdn.redditcfb.com/60x40/cfb/sandiegostate.png',
    'San José State': 'https://cdn.redditcfb.com/60x40/cfb/sanjosestate.png',
    'South Alabama': 'https://cdn.redditcfb.com/60x40/cfb/southalabama.png',
    'South Carolina': 'https://cdn.redditcfb.com/60x40/cfb/southcarolina.png',
    'South Florida': 'https://cdn.redditcfb.com/60x40/cfb/usf.png',
    'Southern Miss': 'https://cdn.redditcfb.com/60x40/cfb/southernmiss.png',
    'Stanford': 'https://cdn.redditcfb.com/60x40/cfb/stanford.png',
    'Syracuse': 'https://cdn.redditcfb.com/60x40/cfb/syracuse.png',
    'TCU': 'https://cdn.redditcfb.com/60x40/cfb/tcu.png',
    'Temple': 'https://cdn.redditcfb.com/60x40/cfb/temple.png',
    'Tennessee': 'https://cdn.redditcfb.com/60x40/cfb/tennessee.png',
    'Texas': 'https://cdn.redditcfb.com/60x40/cfb/texas.png',
    'Texas A&M': 'https://cdn.redditcfb.com/60x40/cfb/texasam.png',
    'Texas State': 'https://cdn.redditcfb.com/60x40/cfb/texasstate.png',
    'Texas Tech': 'https://cdn.redditcfb.com/60x40/cfb/texastech.png',
    'Toledo': 'https://cdn.redditcfb.com/60x40/cfb/toledo.png',
    'Troy': 'https://cdn.redditcfb.com/60x40/cfb/troy.png',
    'Tulane': 'https://cdn.redditcfb.com/60x40/cfb/tulane.png',
    'Tulsa': 'https://cdn.redditcfb.com/60x40/cfb/tulsa.png',
    'UAB': 'https://cdn.redditcfb.com/60x40/cfb/uab.png',
    'UCF': 'https://cdn.redditcfb.com/60x40/cfb/ucf.png',
    'UCLA': 'https://cdn.redditcfb.com/60x40/cfb/ucla.png',
    'UConn': 'https://cdn.redditcfb.com/60x40/cfb/connecticut.png',
    'UL Monroe': 'https://cdn.redditcfb.com/60x40/cfb/ulm.png',
    'UNLV': 'https://cdn.redditcfb.com/60x40/cfb/unlv.png',
    'USC': 'https://cdn.redditcfb.com/60x40/cfb/usc.png',
    'UTEP': 'https://cdn.redditcfb.com/60x40/cfb/utep.png',
    'UTSA': 'https://cdn.redditcfb.com/60x40/cfb/utsa.png',
    'Utah': 'https://cdn.redditcfb.com/60x40/cfb/utah.png',
    'Utah State': 'https://cdn.redditcfb.com/60x40/cfb/utahstate.png',
    'Vanderbilt': 'https://cdn.redditcfb.com/60x40/cfb/vanderbilt.png',
    'Virginia': 'https://cdn.redditcfb.com/60x40/cfb/virginia.png',
    'Virginia Tech': 'https://cdn.redditcfb.com/60x40/cfb/virginiatech.png',
    'Wake Forest': 'https://cdn.redditcfb.com/60x40/cfb/wakeforest.png',
    'Washington': 'https://cdn.redditcfb.com/60x40/cfb/washington.png',
    'Washington State': 'https://cdn.redditcfb.com/60x40/cfb/washingtonstate.png',
    'West Virginia': 'https://cdn.redditcfb.com/60x40/cfb/westvirginia.png',
    'Western Kentucky': 'https://cdn.redditcfb.com/60x40/cfb/wku.png',
    'Western Michigan': 'https://cdn.redditcfb.com/60x40/cfb/westernmichigan.png',
    'Wisconsin': 'https://cdn.redditcfb.com/60x40/cfb/wisconsin.png',
    'Wyoming': 'https://cdn.redditcfb.com/60x40/cfb/wyoming.png',
}


def get_flair_icon_url(school: str) -> str | None:
    return FLAIR_ICON_URLS.get(school)
